export const FAQS = [
  {
    id: "Q.01",
    page: "P.01",
    tag: "ABOUT",
    accent: "coral",
    q: "What is Zevo Works?",
    a: "Zevo Works is a one-person studio building AI-powered tools that automate tedious knowledge work. Right now there's one shipped tool — my-resume, an ATS-optimised résumé builder. More are being drafted; each one ships small, fast, and free.",
    seeAlso: ["Q.02", "Q.04"],
  },
  {
    id: "Q.02",
    page: "P.02",
    tag: "PRICING",
    accent: "mint",
    q: "Is my-resume really free?",
    a: "Yes. ₹0 — no credit card, no trial limits, no paywall on the core resume generation. We may add optional paid extras in the future, but generating a tailored résumé will always be free.",
    seeAlso: ["Q.01"],
  },
  {
    id: "Q.03",
    page: "P.03",
    tag: "TECH",
    accent: "gold",
    q: "What does ATS-optimised mean?",
    a: "Most companies run résumés through Applicant Tracking System (ATS) software before a human sees them. my-resume formats every résumé to pass these filters: clean structure, parseable text, the right keywords from the job description, and no exotic fonts or tables that break the parser.",
    seeAlso: ["Q.04", "Q.05"],
  },
  {
    id: "Q.04",
    page: "P.04",
    tag: "TECH",
    accent: "gold",
    q: "How does the AI tailor my résumé to a JD?",
    a: "Paste the job description; my-resume's pipeline extracts the critical skills, seniority signals, and recruiter priorities, then rewrites bullet points and reorders sections to match — without inventing experience you don't have. Every output is JSON-typed and eval-gated.",
    seeAlso: ["Q.03"],
  },
  {
    id: "Q.05",
    page: "P.05",
    tag: "FORMAT",
    accent: "mint",
    q: "What file format do I get?",
    a: "A PDF/A résumé, typeset with LaTeX for pixel-perfect output. You can preview it in the browser and download whenever you're ready to apply. One page by default.",
    seeAlso: ["Q.03"],
  },
  {
    id: "Q.06",
    page: "P.06",
    tag: "PRIVACY",
    accent: "coral",
    q: "Is my data safe?",
    a: "Your résumé content stays on our servers only as long as you keep your account. You can delete your account and all associated data at any time from the dashboard. We never sell or share input data.",
    seeAlso: ["Q.02"],
  },
];
